import type { Policy } from "./types";

export const DEFAULT_POLICIES: Policy[] = [
  {
    id: "fs.recursive_delete",
    group: "filesystem",
    title: "Recursive delete of system paths",
    description: "Block rm/find -delete targeting /, $HOME, or other system roots.",
    enabled: true,
    action: "block",
    severity: "critical",
  },
  {
    id: "fs.sensitive_delete",
    group: "filesystem",
    title: "Delete of credential files",
    description: "Block removal of .env, keys, pem files, and credential stores.",
    enabled: true,
    action: "block",
    severity: "high",
  },
  {
    id: "fs.disk_wipe",
    group: "filesystem",
    title: "Disk and filesystem wipe",
    description: "Block mkfs, dd of=/dev, shred, and similar destructive disk ops.",
    enabled: true,
    action: "block",
    severity: "critical",
  },
  {
    id: "fs.sensitive_read",
    group: "filesystem",
    title: "Sensitive file read",
    description: "Allow the read, then force DLP redaction of the tool result.",
    enabled: true,
    action: "redact",
    severity: "high",
  },
  {
    id: "git.force_push",
    group: "git",
    title: "Force push",
    description: "Block git push --force and --force-with-lease.",
    enabled: true,
    action: "block",
    severity: "high",
  },
  {
    id: "git.hard_reset",
    group: "git",
    title: "Hard reset / clean",
    description: "Block git reset --hard and git clean -fdx outside a snapshot.",
    enabled: true,
    action: "block",
    severity: "high",
  },
  {
    id: "sql.ddl_drop",
    group: "sql",
    title: "Destructive DDL",
    description: "Block DROP, TRUNCATE, and ALTER that remove data or tables.",
    enabled: true,
    action: "block",
    severity: "critical",
  },
  {
    id: "sql.unbounded_mutation",
    group: "sql",
    title: "Unbounded UPDATE/DELETE",
    description: "Block mutations with no WHERE, or WHERE 1=1.",
    enabled: true,
    action: "block",
    severity: "critical",
  },
  {
    id: "net.egress_unlisted",
    group: "network",
    title: "Unauthorized egress",
    description: "Block curl/wget/fetch to hosts outside the allowlist.",
    enabled: true,
    action: "block",
    severity: "high",
  },
  {
    id: "net.pipe_to_shell",
    group: "network",
    title: "Remote script execution",
    description: "Block curl | sh, wget | bash, and npm postinstall pipes.",
    enabled: true,
    action: "block",
    severity: "critical",
  },
  {
    id: "shell.eval_obfuscation",
    group: "shell",
    title: "Obfuscated execution",
    description: "Block eval, base64-decoded pipes, IFS tricks, and encoded payloads.",
    enabled: true,
    action: "block",
    severity: "critical",
  },
  {
    id: "shell.fork_bomb",
    group: "shell",
    title: "Fork bomb and process kill",
    description: "Block :(){ :|:& };: and kill -9 -1.",
    enabled: true,
    action: "block",
    severity: "critical",
  },
  {
    id: "shell.chmod_world",
    group: "shell",
    title: "World-writable permissions",
    description: "Block chmod 777 and recursive world-writable changes.",
    enabled: true,
    action: "block",
    severity: "high",
  },
  {
    id: "mcp.path_escape",
    group: "mcp",
    title: "Path escape from workspace",
    description: "Block filesystem MCP writes outside the project root.",
    enabled: true,
    action: "block",
    severity: "high",
  },
  {
    id: "secrets.exfil",
    group: "secrets",
    title: "Credential exfiltration",
    description: "Block shipping keys, .env files, or private keys over the network.",
    enabled: true,
    action: "block",
    severity: "critical",
  },
];

export const EGRESS_ALLOWLIST = [
  "api.github.com",
  "registry.npmjs.org",
  "api.openai.com",
  "api.anthropic.com",
  "api.x.ai",
];
