/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as GatewaysRouteImport } from './routes/gateways'
import { Route as InterceptRouteImport } from './routes/intercept'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as SnapshotsRouteImport } from './routes/snapshots'
import { Route as VaultRouteImport } from './routes/vault'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const GatewaysRoute = GatewaysRouteImport.update({
  id: '/gateways',
  path: '/gateways',
  getParentRoute: () => rootRouteImport,
} as any)
const InterceptRoute = InterceptRouteImport.update({
  id: '/intercept',
  path: '/intercept',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const SnapshotsRoute = SnapshotsRouteImport.update({
  id: '/snapshots',
  path: '/snapshots',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/config': typeof ConfigRoute
  '/gateways': typeof GatewaysRoute
  '/intercept': typeof InterceptRoute
  '/policies': typeof PoliciesRoute
  '/snapshots': typeof SnapshotsRoute
  '/vault': typeof VaultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/config': typeof ConfigRoute
  '/gateways': typeof GatewaysRoute
  '/intercept': typeof InterceptRoute
  '/policies': typeof PoliciesRoute
  '/snapshots': typeof SnapshotsRoute
  '/vault': typeof VaultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/config': typeof ConfigRoute
  '/gateways': typeof GatewaysRoute
  '/intercept': typeof InterceptRoute
  '/policies': typeof PoliciesRoute
  '/snapshots': typeof SnapshotsRoute
  '/vault': typeof VaultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/config'
    | '/gateways'
    | '/intercept'
    | '/policies'
    | '/snapshots'
    | '/vault'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/config'
    | '/gateways'
    | '/intercept'
    | '/policies'
    | '/snapshots'
    | '/vault'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/config'
    | '/gateways'
    | '/intercept'
    | '/policies'
    | '/snapshots'
    | '/vault'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  ConfigRoute: typeof ConfigRoute
  GatewaysRoute: typeof GatewaysRoute
  InterceptRoute: typeof InterceptRoute
  PoliciesRoute: typeof PoliciesRoute
  SnapshotsRoute: typeof SnapshotsRoute
  VaultRoute: typeof VaultRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gateways': {
      id: '/gateways'
      path: '/gateways'
      fullPath: '/gateways'
      preLoaderRoute: typeof GatewaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intercept': {
      id: '/intercept'
      path: '/intercept'
      fullPath: '/intercept'
      preLoaderRoute: typeof InterceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snapshots': {
      id: '/snapshots'
      path: '/snapshots'
      fullPath: '/snapshots'
      preLoaderRoute: typeof SnapshotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  ConfigRoute: ConfigRoute,
  GatewaysRoute: GatewaysRoute,
  InterceptRoute: InterceptRoute,
  PoliciesRoute: PoliciesRoute,
  SnapshotsRoute: SnapshotsRoute,
  VaultRoute: VaultRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
